import { createCategory, deleteCategory } from "./menu.js";

export const elements = {
    itemGrid: document.getElementById("items-grid")! as HTMLDivElement,
    createItemBtn: document.getElementById("create-item-btn")! as HTMLButtonElement,
    createItemModal: document.getElementById("modal-menu-item")! as HTMLDivElement,
    createItemModalBtn: document.getElementById("create-item-modal-btn")! as HTMLButtonElement,
    cancelItemBtn: document.getElementById("cancel-modal-btn")! as HTMLButtonElement,
    closeItemBtn: document.getElementById("close-modal-btn")! as HTMLButtonElement,
    itemName: document.getElementById("item-name")! as HTMLInputElement,
    itemPrice: document.getElementById("item-price")! as HTMLInputElement,
    createCategoryBtn: document.getElementById("create-category")! as HTMLButtonElement,
    categoryCreationModal: document.getElementById("modal-new-category")! as HTMLDivElement,
    categoryName: document.getElementById("category-name")! as HTMLInputElement,
    categoryIcon: document.getElementById("category-icon")! as HTMLInputElement,
    createCategoryBtnFinal: document.getElementById("create-btn-category")! as HTMLButtonElement,
    cancelCategorybtn: document.getElementById("cancel-category-create")! as HTMLButtonElement,
    closeCategoryCreate: document.getElementById("close-category-create")! as HTMLButtonElement,
    categoryGrid: document.getElementById("card grid")! as HTMLUListElement,
    itemCategory: document.getElementById("item-category")! as HTMLSelectElement,
    deleteItemModal: document.getElementById("modal-delete-item")! as HTMLDivElement,
    deleteItemConfirm: document.getElementById("modal-delete-item-confirm")! as HTMLButtonElement,
    deleteCategoryModal: document.getElementById("modal-delete-category")! as HTMLDivElement,
    deleteCategoryConfirm: document.getElementById("modal-delete-category-confirm")! as HTMLButtonElement,
    itemDesc: document.getElementById("item-desc")! as HTMLInputElement,
    tabModal: document.getElementById("modal-new-tab")! as HTMLDivElement,
    tabTableNum: document.getElementById("new-tab-table")! as HTMLInputElement,
    tabCustomerName: document.getElementById("new-tab-customer")! as HTMLInputElement,
    tabNotes: document.getElementById("new-tab-notes")! as HTMLInputElement,
    tabsGrid: document.getElementById("tabs-grid-67")! as HTMLDivElement,
    createTabBtn: document.getElementById("create-tab-btn")! as HTMLButtonElement,
    cancelTabBtn: document.getElementById("create-tab-cancel")! as HTMLButtonElement,
    closeTabBtn: document.getElementById("close-tab-modal")! as HTMLButtonElement,
    tabModalBtn: document.getElementById("new-tab-btn")! as HTMLButtonElement,

}